# Generated by Django 5.1.4 on 2025-01-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentManagementNewAgentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agent_id", models.BigIntegerField(null=True)),
                ("name", models.CharField(max_length=300)),
                ("phone", models.IntegerField()),
                ("district", models.CharField(max_length=500, null=True)),
                ("place", models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
