# Generated by Django 5.1.4 on 2025-01-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mio_agents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agentmanagementnewagentmodel",
            name="phone",
            field=models.CharField(max_length=15),
        ),
    ]
