# Generated by Django 5.1.5 on 2025-01-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.BigIntegerField(null=True)),
                ('name', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=15)),
                ('district', models.CharField(max_length=500, null=True)),
                ('place', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
